FROM python:3.8.10-buster

# Use the Korean official mirror in non-production environments
RUN if [ ${env} != "production" ]; then \
    cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
    sed -i s%http://deb.debian.org/debian%http://ftp.kr.debian.org/debian% /etc/apt/sources.list; \
    fi

# System setup
RUN apt-get update && pip3 install --upgrade pip

# Install related packages
RUN pip install \
    numpy==1.22.3 \
    pandas==1.2.0 \
    cx-Oracle==8.2.1 \
    structlog==20.1.0 \
    python-dotenv==0.13.0 \
    attrs==19.3.0 \
    cattrs==1.0.0 \
    click==7.1.2 \
    notebook==6.4.12 \
    pytest==6.2.5 \
    SQLAlchemy===1.4.31 \
    tensorboard

# Install pytorch
RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

WORKDIR /ibk-personnel-placement

COPY . /ibk-personnel-placement

EXPOSE 8080